### PR TITLE
Fixed join/part line modification panic

### LINKED ISSUE #227: Join/Part messages overflow
Saw this randomly when a bunch of people all joined/parted at the same time. It somehow corrected itself eventually, but still worth some investigation.

image

### PR DESCRIPTION
**Pull request by trevarj**
When multiple users join/part from a channel at the same timestamp, the line gets modified. This wasn't invalidating the height calulation so it was causing an overflow if many people join/part or if your screen is small and it needs to wrap that line after modification.

Ugh, basically what I did for a fix is just add a way to force invalidating the height of the line when it's modified. Didn't think about this when I added `LineDataCache` for height calculation.

Closes #227

### CODE REVIEW

**Comment by trevarj** [comment]
Closes #227

File: libtiny_tui/src/msg_area/line.rs [hunk 1]
```diff
@@ -149,8 +149,12 @@ impl Line {
         self.len_chars += 1;
     }
 
-    /// How many lines does this take when rendered? O(n) where n = number of
-    /// split positions in the line (i.e. whitespaces).
+    pub(crate) fn force_recalculation(&mut self) {
```
Comment (trevarj) [inline libtiny_tui/src/msg_area/line.rs:152]: Not sure if this actually needs to be `pub(crate)`. `pub` might be the right choice, but I'm not sure if matters.

File: libtiny_tui/src/msg_area/line.rs [hunk 2]
```diff
@@ -149,8 +149,12 @@ impl Line {
         self.len_chars += 1;
     }
 
-    /// How many lines does this take when rendered? O(n) where n = number of
-    /// split positions in the line (i.e. whitespaces).
```
Comment (osa1) [inline libtiny_tui/src/msg_area/line.rs:153]: Why was this comment removed? Is this not valid anymore?

**Comment by osa1** [comment]
LGTM, thanks @trevarj ! Added one inline question.

File: libtiny_tui/src/msg_area/line.rs (hunk 2 above)
Comment (trevarj) [reply libtiny_tui/src/msg_area/line.rs:153]: Yeah, it's O(n) where n is the size of the buffer
